# Generated by Django 3.1.4 on 2020-12-05 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VibrationPattern',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('pattern', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='VibrationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('isAlarm', models.BooleanField(default=False)),
                ('alarmTimeTo', models.CharField(max_length=128, null=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vibrationPatternName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vibration.vibrationpattern')),
            ],
        ),
    ]
