# Generated by Django 3.1.4 on 2020-12-04 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vibration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vibrationpattern',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='vibrationpattern',
            name='value',
        ),
        migrations.RemoveField(
            model_name='vibrationpattern',
            name='vibrationSettingID',
        ),
        migrations.AddField(
            model_name='vibrationpattern',
            name='pattern',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='vibrationsetting',
            name='vibrationPatternID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vibration.vibrationpattern'),
        ),
    ]
