# Generated by Django 3.1.4 on 2020-12-04 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepAnalysisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleepScore', models.FloatField(null=True)),
                ('sleepTimeFrom', models.CharField(max_length=128, null=True)),
                ('sleepTimeTo', models.CharField(max_length=128, null=True)),
                ('deepSleepTime', models.IntegerField(null=True)),
                ('shallowSleepTime', models.IntegerField(null=True)),
                ('evalulation', models.CharField(max_length=256, null=True)),
                ('sleepDate', models.DateField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EEGData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.IntegerField()),
                ('sleepAnalysisResultID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sleep_analysis.sleepanalysisresult')),
            ],
        ),
    ]
