# Generated by Django 3.1.4 on 2020-12-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sleepanalysisresult',
            old_name='deepSleepTime',
            new_name='deepSleepScore',
        ),
        migrations.RenameField(
            model_name='sleepanalysisresult',
            old_name='shallowSleepTime',
            new_name='shallowSleepScore',
        ),
    ]
